services:
  inventario:
    image: inventario
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: inventario-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    networks:
      - spring-network
    depends_on:
      - postgres14
    entrypoint: ["sh", "-c", "sleep 10 && java -jar /root/ms-invetario-0.0.1-SNAPSHOT.jar"]
  postgres14:
    image: postgres14-alpine
    container_name: postgres_database
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: inventario_db
    ports:
      - "5532:5432"
    networks:
      - spring-network
    volumes:
      - postgres-volume:/var/lib/postgresql/data
networks:
  spring-network:
    external: true
volumes:
  postgres-volume: