services:
  productos:
    image: productos
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: productos-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - spring-network
    depends_on:
      - mysql
    entrypoint: ["sh", "-c", "sleep 10 && java -jar /root/ms-productos-0.0.1-SNAPSHOT.jar"]
  mysql:
    image: mysql
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: productos_db
    ports:
      - "3307:3306"
    networks:
      - spring-network
    volumes:
      - mysql-volume:/var/lib/mysql
networks:
  spring-network:
    external: true
volumes:
  mysql-volume: